import type { Metadata } from "next";
// Geist uses CSS variables with font-display: swap for fast text render
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import { TopBlurBar } from "@/components/ui/TopBlurBar";
import ClientProviders from "./client-providers";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${GeistMono.variable}`}
      suppressHydrationWarning
    >
      <body className={`${GeistSans.className} antialiased`}>
        <ThemeProvider>
          <ClientProviders>
            <TopBlurBar />
            <div className="fixed top-4 right-4 z-[10000]">
              <ThemeToggle />
            </div>
            {children}
          </ClientProviders>
        </ThemeProvider>
      </body>
    </html>
  );
}
