/**
 * From Single Products to Complementary Sets at IKEA (Complete the Look)
 * — body copy for the project detail page.
 */
export const ikeaComplementarySetsCopy = {
  theSolution: {
    heading: "The solution",
    content: `Complete the Look is a 3D-led shopping experience that enables customers to explore and select complementary furniture and accessories as part of a single, continuous decision.

Embedded within the product page, the experience allows users to add, remove, and customise related items directly in spatial context, one at a time - without restarting their journey. Products are placed with accurate scale and positioning, enabling customers to judge proportion, compatibility, and overall coherence before committing.

The result is a shift from isolated product selection toward composed decision-making, supporting both user confidence and more meaningful basket growth.`,
  },
  whyThisMattered: {
    heading: "Why this mattered",
    content: `Furniture is rarely purchased as a single object.

Yet most online shopping flows are optimised for one product at a time. When customers want to buy complementary items, say, chairs for a desk, lighting for a workspace, accessories for storage - they are required to restart the process repeatedly: new pages, new filters, new evaluations.

This created two compounding issues:
- User friction: increased cognitive load and decision fatigue when assembling setups
- Business inefficiency: carts anchored around a single "safe" item, with complementary products often deferred or abandoned

The opportunity was not to increase attachment through bundles or discounts, but to reduce effort and increase relevance by supporting how people actually make furnishing decisions.`,
  },
  designIntent: {
    heading: "Design Intent",
    content: `The core design intent was to shift from sequential product selection to composed decision-making.

Key principles:
- Keep complementary products within the same decision space
- Preserve user control and pacing
- Reduce cognitive load through spatial clarity
- Avoid forced bundles or price shock`,
  },
  theExperience: {
    heading: "The Experience",
    content: `Inside the 3D view, the product gains company.
When activated:
- Users see a curated list of complementary items
- Items can be added one at a time into the same 3D scene
- Each item is placed with correct scale, orientation, and position
- Items can be removed or customised freely

The experience supports exploration without assuming purchase intent.`,
  },
  howUsersReacted: {
    heading: "How users reacted",
    content: `User testing showed:
- Strong perceived value of spatial context
- Increased confidence in multi-product decisions
- Higher engagement with complementary items

The concept achieved an NPS of 86 during PoC testing, indicating both usability and relevance.`,
  },
  userQuote: `"I love the idea. It's very intuitive. I mean everybody already loves IKEA but this just really makes it easier if you don't have a showroom nearby." — User, United Kingdom`,
  roleOfAI: {
    heading: "Role of AI",
    content: `Recommendations in Complete the Look are generated by an ML-based system developed in collaboration with IKEA's AI Lab.

The system does not optimise for maximum attachment or basket size in isolation. Instead, it balances multiple signals to support relevance and decision comfort at the moment a user is considering complementary items.

Key inputs include:
- Home furnishing knowledge, derived from interior design rules and product relationships
- Style and colour compatibility, based on the selected product and variant
- Behavioural signals, informed by existing recommendation models
- Price sensitivity and effort to buy, accounting for relative price, commitment level, and typical purchase friction

Price is treated not as a ranking shortcut, but as a pacing mechanism. Lower-effort, lower-commitment items are surfaced earlier, while higher-priced or higher-commitment products appear later in the sequence. This helps reduce decision fatigue and avoids sudden price escalation, while preserving user control.

Importantly, this intelligence remains implicit. Users are not asked to interpret why something is suggested; they evaluate recommendations based on how well they fit the emerging setup.`,
  },
  closing: {
    heading: "Closing",
    content: `Complete the Look demonstrates a shift from isolated product selection to composed decision-making, using spatial context and AI-assisted curation to reduce effort and support confident choices.`,
  },
  personalInsight: {
    heading: "Personal Insight",
    content: `When users are in the complete the look mode, they are more interested in how the items fit into their broader space. The visualisation of items together helps them transform their abstract imagination into something more concrete and visual.

They look at the relative sizing of items, check colour coordination, how it fits with the main product, about their spatial arrangement, etc. instead of a "boring piece of furniture" — quote from a user.

The users transition from a "does this product work?" to a "how can this product work in my space?" mentality. And I think the experience transitions from a transactional to a more experiential feeling.

Also, they move from a detailed product examination to contextualising the product seems natural to them — almost like going from a functional assessment to an emotional/aesthetic planning.`,
  },
  impactDummy: `The workspace focused range experience was tested in 16 markets:

+ 9.3% increase in Add to cart
+ 30% increase in unique items per Add to cart event
+ 14.6% increase in Add to cart revenue per Add to cart event
+ 18.7% increase in Add to cart revenue per user`,
} as const;

export type IkeaComplementarySetsContentKey = keyof typeof ikeaComplementarySetsCopy;
